SELECT
    b.DESCRIPTION,
    D.NAME,
    COUNT(a.TERM_TYPE_SID) AS TERMINAL_COUNT
FROM
    IQTPS.NODE_TYPE_TERM a
JOIN
    IQTPS.TERM_TYPE b ON b.TERM_TYPE_SID = a.TERM_TYPE_SID
JOIN
    DIEBOLD.LOCATIONDESCRIPTION c ON a.NODE_SID = c.TERMID
LEFT JOIN
    IQTPS.TERMSUBTYPE D ON a.SUBTYPE = D.SUBTYPE
WHERE
    a.PROFILE_SID = -1
    AND a.NODE_SID IN (SELECT node_sid FROM IQTPS.NODE WHERE status = 'ACT')
   --AND (a.TERM_TYPE_SID = 2213 OR D.SUBTYPE IS NULL)  -- This condition shows ONLY 2213 reader types, or is the subtype is NULL
GROUP BY
    a.TERM_TYPE_SID,
    b.DESCRIPTION,
    D.NAME
ORDER BY
    b.DESCRIPTION ASC;